@extends('errors.layout')
@section('code', '404')
@section('icon', 'fa-compass')
@section('heading', 'Página no encontrada')
@section('message', 'La página que buscas no existe o cambió de lugar. Revisa la dirección o vuelve al inicio.')
